[y1,fs1] = audioread("music_ceiling-fan.wav");
[s1,f1,t1] = stft(y1,fs1);
figure;
surf(t1,f1,abs(s1));
colorbar;
xlabel("Time t");
ylabel("Frequency f");
zlabel("Magnitude");
title("STFT Plot for Music+Ceiling-fan");
figure;
stft(y1,fs1);
S1 = sum(transpose(abs(s1)));
amp1 = S1/max(S1);

[y2,fs2] = audioread("music_city-traffic.wav");
[s2,f2,t2] = stft(y2,fs2);
figure;
surf(t2,f2,abs(s2));
colorbar;
xlabel("Time t");
ylabel("Frequency f");
zlabel("Magnitude");
title("STFT Plot for Music+City-traffic");
figure;
stft(y2,fs2);
S2 = sum(transpose(abs(s2)));
amp2 = S2/max(S2);

[y3,fs3] = audioread("music_pressure-cooker.wav");
[s3,f3,t3] = stft(y3,fs3);
figure;
surf(t3,f3,abs(s3));
colorbar;
xlabel("Time t");
ylabel("Frequency f");
zlabel("Magnitude");
title("STFT Plot for Music+Pressure-Cooker");
figure;
stft(y3,fs3);
S3 = sum(transpose(abs(s3)));
amp3 = S3/max(S3);

[y4,fs4] = audioread("music_water-pump.wav");
[s4,f4,t4] = stft(y4,fs4);
figure;
surf(t4,f4,abs(s4));
colorbar;
xlabel("Time t");
ylabel("Frequency f");
zlabel("Magnitude");
title("STFT Plot for Music+Water-Pump");
figure;
stft(y4,fs4);
S4 = sum(transpose(abs(s4)));
amp4 = S4/max(S4);

[yin,Fs_in] = audioread(InputFile);
[sin,fin,tin] = stft(yin,Fs_in);
figure;
surf(tin,fin,abs(sin));
xlabel("Time t");
ylabel("Frequency f");
zlabel("Magnitude");
title("STFT Plot for InputAudioFile");
figure;
stft(yin,Fs_in)
Sin = sum(transpose(abs(sin)));
amp_in = Sin/max(Sin);

figure;
subplot 221;
plot(f1,amp1);
grid on;
xlabel("Frequency f");
ylabel("Normalised Magnitude");
title("STFT varying only with Frequency for Music+Ceiling-fan");
subplot 222;
plot(f2,amp2);
grid on;
xlabel("Frequency f");
ylabel("Normalised Magnitude");
title("STFT varying only with Frequency for Music+City-traffic");
subplot 223;
plot(f3,amp3);
grid on;
xlabel("Frequency f");
ylabel("Normalised Magnitude");
title("STFT varying only with Frequency for Music+Pressure-Cooker");
subplot 224;
plot(f4,amp4);
grid on;
xlabel("Frequency f");
ylabel("Normalised Magnitude");
title("STFT varying only with Frequency for Music+Water-Pump");

figure;
plot(fin,amp_in); 
grid on;
xlabel("Frequency f");
ylabel("Normalised Magnitude");
title("STFT varying only with Frequency for InputAudioFile");